const express = require('express');
const router = express.Router();

// Import route modules
const spesialisasiRoutes = require('./spesialisasi/spesialisasi.route');
const userRoutes = require('./users/user.route');
const pasienRoutes = require('./pasien/pasien.route');
const doctorRoutes = require('./doctors/doctor.route');
const provinsiRoutes = require('./provinsi/provinsi.route');
const kotaRoutes = require('./kota/kota.route');
const adminRoutes = require('./admin/admin.route');
const apotekRoutes = require('./apotek/apotek.route');
const apotekerRoutes = require('./apoteker/apoteker.route');
const kategoriArtikelRoutes = require('./kategori_artikel/kategori_artikel.route');
const artikelKesehatanRoutes = require('./artikel_kesehatan/artikel_kesehatan.route');
const faqRoutes = require('./faq/faq.route');
const kategoriObatRoutes = require('./kategori_obat/kategori_obat.route');
const kurirRoutes = require('./kurir/kurir.route');
const obatRoutes = require('./obat/obat.route');
const promoRoutes = require('./promo/promo.route');
const rumahSakitRoutes = require('./rumah_sakit/rumah_sakit.route');
const klinikRoutes = require('./klinik/klinik.route');
const konsultasiRoutes = require('./konsultasi/konsultasi.route');
const resepRoutes = require('./resep/resep.route');
const pembayaranRoutes = require('./payment/payment.route');
const systemSettingsRoutes = require('./system_settings/system_settings.route');
const stokObatRoutes = require('./stok_obat/stok_obat.route');
const pengirimanRoutes = require('./pengiriman/pengiriman.route');
const detailResepRoutes = require('./detail_resep/detail_resep.route');
const medicalRecordRoutes = require('./medical_record/medical_record.route');
const vitalSignsRoutes = require('./vital_signs/vital_signs.route');
const notifikasiRoutes = require('./notifikasi/notifikasi.route');
const reviewRatingRoutes = require('./review_rating/review_rating.route');
const feedbackRoutes = require('./feedback/feedback.route');
const chatMessagesRoutes = require('./chat_messages/chat_messages.route');
const jadwalDoctorRoutes = require('./jadwal_doctor/jadwal_doctor.route');
const appointmentRoutes = require('./appointment/appointment.route');
const logsRoutes = require('./logs/logs.route');

// Define API routes
router.use('/spesialisasi', spesialisasiRoutes);
router.use('/users', userRoutes);
router.use('/pasien', pasienRoutes);
router.use('/doctors', doctorRoutes);
router.use('/provinsi', provinsiRoutes);
router.use('/kota', kotaRoutes);
router.use('/admin', adminRoutes);
router.use('/apotek', apotekRoutes);
router.use('/apoteker', apotekerRoutes);
router.use('/kategori_artikel', kategoriArtikelRoutes);
router.use('/artikel_kesehatan', artikelKesehatanRoutes);
router.use('/faq', faqRoutes);
router.use('/kategori_obat', kategoriObatRoutes);
router.use('/kurir', kurirRoutes);
router.use('/obat', obatRoutes);
router.use('/promo', promoRoutes);
router.use('/rumah_sakit', rumahSakitRoutes);
router.use('/klinik', klinikRoutes);
router.use('/konsultasi', konsultasiRoutes);
router.use('/resep', resepRoutes);
router.use('/pembayaran', pembayaranRoutes);
router.use('/system_settings', systemSettingsRoutes);
router.use('/stok_obat', stokObatRoutes);
router.use('/pengiriman', pengirimanRoutes);
router.use('/detail_resep', detailResepRoutes);
router.use('/medical_record', medicalRecordRoutes);
router.use('/vital_signs', vitalSignsRoutes);
router.use('/notifikasi', notifikasiRoutes);
router.use('/review_rating', reviewRatingRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/chat_messages', chatMessagesRoutes);
router.use('/jadwal_doctor', jadwalDoctorRoutes);
router.use('/appointment', appointmentRoutes);
router.use('/logs', logsRoutes);

module.exports = router;
